function isEnvEnabled(value: unknown) {
  return value === 'true';
}

const USE_BACKEND_MIGRATED_QUERIES_ALL = isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES);

export const USE_BACKEND_MIGRATED_QUERIES_ORGS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_ORGS);
export const USE_BACKEND_MIGRATED_QUERIES_USERS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_USERS);
export const USE_BACKEND_MIGRATED_QUERIES_TASKS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_TASKS);
export const USE_BACKEND_MIGRATED_QUERIES_RUNS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_RUNS);
export const USE_BACKEND_MIGRATED_QUERIES_ASSIGNMENTS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_ASSIGNMENTS);
export const USE_BACKEND_MIGRATED_QUERIES_ADMINISTRATIONS =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_ADMINISTRATIONS);
export const USE_BACKEND_MIGRATED_QUERIES_LEGAL =
  USE_BACKEND_MIGRATED_QUERIES_ALL || isEnvEnabled(import.meta.env.VITE_USE_BACKEND_MIGRATED_QUERIES_LEGAL);

export const USE_BACKEND_MIGRATED_QUERIES = USE_BACKEND_MIGRATED_QUERIES_ALL;
