// This file is auto-generated by setup-test-user-preserve.js
// Last updated: 2025-05-06T00:35:55.116Z
export const TEST_USER_ID = 'h5f1pRFi2rtvQf9gWuxqCFzXqstw';
export const TEST_USER_EMAIL = '7vpqcm4ihi@levante.com'; 