name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances

    env:
      CI: true

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.LEVANTE_BOT_APP_ID }}
          private_key: ${{ secrets.LEVANTE_BOT_APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout firebase-functions repo
        uses: actions/checkout@v4
        with:
          repository: levante-framework/firebase-functions
          path: firebase-functions
          token: ${{ steps.generate_token.outputs.token }}

            - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run E2E tests with Docker
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          # Build and run Docker container
          docker build -t levante-e2e .
          docker run --rm \
            -e CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY \
            -e GITHUB_TOKEN=$GITHUB_TOKEN \
            -v ${{ github.workspace }}/cypress/screenshots:/app/cypress/screenshots \
            -v ${{ github.workspace }}/cypress/videos:/app/cypress/videos \
            levante-e2e

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: cypress/screenshots/

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos-${{ matrix.containers }}
          path: cypress/videos/
