name: Run all cypress tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Rewrite package.json with token for levante-zod
        run: |
          sed -i 's~"levante-zod": ".*"~"levante-zod": "https://${{ secrets.GH_PAT }}@github.com/levante-framework/levante-zod.git"~' package.json

      - name: Install dependencies
        run: npm install

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run dev:db
