name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    env:
      CI: true

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.LEVANTE_BOT_APP_ID }}
          private_key: ${{ secrets.LEVANTE_BOT_APP_PRIVATE_KEY }}

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout firebase-functions repo
        uses: actions/checkout@v4
        with:
          repository: levante-framework/firebase-functions
          path: firebase-functions
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          docker build -t levante-e2e .
          docker run --rm \
            -e CI=true \
            -e NODE_ENV=development \
            -e VITE_EMULATOR=TRUE \
            -e VITE_FIREBASE_PROJECT=DEV \
            -e VITE_LEVANTE=TRUE \
            -e VITE_QUERY_DEVTOOLS_ENABLED=false \
            -e CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }} \
            -e GITHUB_TOKEN=${{ steps.generate_token.outputs.token }} \
            -v ${{ github.workspace }}:/e2e \
            levante-e2e

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.containers }}
          path: cypress/screenshots/

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos-${{ matrix.containers }}
          path: cypress/videos/
